# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Accept build arguments for environment variables
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_PUBLIC_API_URL
ARG NEXT_PUBLIC_BASE_PATH
ARG NEXT_PUBLIC_ASSET_PREFIX
ARG NEXT_PUBLIC_ICON_BASE_URL
ARG GOOGLE_VERIFICATION
ARG NEXT_PUBLIC_DOWNLOAD_BAZAR
ARG NEXT_PUBLIC_DOWNLOAD_GOOGLE_PLAY
ARG NEXT_PUBLIC_DOWNLOAD_MYKET
ARG NEXT_PUBLIC_DOWNLOAD_DIRECT
ARG NEXT_PUBLIC_DOWNLOAD_SIBAPP
ARG NEXT_PUBLIC_DOWNLOAD_APPSTAR
ARG NEXT_PUBLIC_DOWNLOAD_IAPPS
ARG NEXT_PUBLIC_DOWNLOAD_SIBIRANI
ARG NEXT_PUBLIC_DOWNLOAD_SIBCHE
ARG NEXT_PUBLIC_DOWNLOAD_PWA
ARG NEXT_PUBLIC_SOCIAL_INSTAGRAM
ARG NEXT_PUBLIC_SOCIAL_TELEGRAM
ARG NEXT_PUBLIC_SOCIAL_LINKEDIN
ARG NEXT_PUBLIC_SOCIAL_TWITTER

# Set production environment
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Set build-time environment variables
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_PUBLIC_API_URL=${NEXT_PUBLIC_PUBLIC_API_URL}
ENV NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
ENV NEXT_PUBLIC_ASSET_PREFIX=${NEXT_PUBLIC_ASSET_PREFIX}
ENV NEXT_PUBLIC_ICON_BASE_URL=${NEXT_PUBLIC_ICON_BASE_URL}
ENV GOOGLE_VERIFICATION=${GOOGLE_VERIFICATION}
ENV NEXT_PUBLIC_DOWNLOAD_BAZAR=${NEXT_PUBLIC_DOWNLOAD_BAZAR}
ENV NEXT_PUBLIC_DOWNLOAD_GOOGLE_PLAY=${NEXT_PUBLIC_DOWNLOAD_GOOGLE_PLAY}
ENV NEXT_PUBLIC_DOWNLOAD_MYKET=${NEXT_PUBLIC_DOWNLOAD_MYKET}
ENV NEXT_PUBLIC_DOWNLOAD_DIRECT=${NEXT_PUBLIC_DOWNLOAD_DIRECT}
ENV NEXT_PUBLIC_DOWNLOAD_SIBAPP=${NEXT_PUBLIC_DOWNLOAD_SIBAPP}
ENV NEXT_PUBLIC_DOWNLOAD_APPSTAR=${NEXT_PUBLIC_DOWNLOAD_APPSTAR}
ENV NEXT_PUBLIC_DOWNLOAD_IAPPS=${NEXT_PUBLIC_DOWNLOAD_IAPPS}
ENV NEXT_PUBLIC_DOWNLOAD_SIBIRANI=${NEXT_PUBLIC_DOWNLOAD_SIBIRANI}
ENV NEXT_PUBLIC_DOWNLOAD_SIBCHE=${NEXT_PUBLIC_DOWNLOAD_SIBCHE}
ENV NEXT_PUBLIC_DOWNLOAD_PWA=${NEXT_PUBLIC_DOWNLOAD_PWA}
ENV NEXT_PUBLIC_SOCIAL_INSTAGRAM=${NEXT_PUBLIC_SOCIAL_INSTAGRAM}
ENV NEXT_PUBLIC_SOCIAL_TELEGRAM=${NEXT_PUBLIC_SOCIAL_TELEGRAM}
ENV NEXT_PUBLIC_SOCIAL_LINKEDIN=${NEXT_PUBLIC_SOCIAL_LINKEDIN}
ENV NEXT_PUBLIC_SOCIAL_TWITTER=${NEXT_PUBLIC_SOCIAL_TWITTER}

# Build the application
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Runtime environment variables should be set when running the container
# They are not needed at build time for the runner stage
# Set defaults (can be overridden at runtime)
ENV NEXT_PUBLIC_SITE_URL=https://eterex.com
ENV NEXT_PUBLIC_API_URL=https://api.eterex.com/api
ENV NEXT_PUBLIC_PUBLIC_API_URL=https://publicv2.eterex.com/public/api
ENV NEXT_PUBLIC_BASE_PATH=
ENV NEXT_PUBLIC_ASSET_PREFIX=
ENV NEXT_PUBLIC_ICON_BASE_URL=https://static-dl.eterex.com/icons-v2/svg
ENV GOOGLE_VERIFICATION=
ENV NEXT_PUBLIC_DOWNLOAD_BAZAR=https://cafebazaar.ir/app/?id=com.eterex&ref=share
ENV NEXT_PUBLIC_DOWNLOAD_GOOGLE_PLAY=https://play.google.com/store/apps/details?id=com.eterex
ENV NEXT_PUBLIC_DOWNLOAD_MYKET=https://myket.ir/app/com.eterex
ENV NEXT_PUBLIC_DOWNLOAD_DIRECT=https://static-dl.eterex.com/eterex.apk
ENV NEXT_PUBLIC_DOWNLOAD_SIBAPP=https://sibapp.com/applications/Eterex_cryptocurrencyexchange?from=search
ENV NEXT_PUBLIC_DOWNLOAD_APPSTAR=https://app-star.store/app.php?id=eterex
ENV NEXT_PUBLIC_DOWNLOAD_IAPPS=https://iapps.ir/app/%D8%A7%D8%AA%D8%B1%D8%A7%DA%A9%D8%B3-%D8%B5%D8%B1%D8%A7%D9%81%DB%8C-%D8%B1%D9%85%D8%B2%D8%A7%D8%B1%D8%B2%D9%87%D8%A7/594739716
ENV NEXT_PUBLIC_DOWNLOAD_SIBIRANI=https://sibirani.com/apps/eterex/
ENV NEXT_PUBLIC_DOWNLOAD_SIBCHE=https://sibche.com/applications/eterax
ENV NEXT_PUBLIC_DOWNLOAD_PWA=https://app.eterex.com
ENV NEXT_PUBLIC_SOCIAL_INSTAGRAM=https://www.instagram.com/eterexchange?utm_medium=copy_link
ENV NEXT_PUBLIC_SOCIAL_TELEGRAM=https://t.me/eterex
ENV NEXT_PUBLIC_SOCIAL_LINKEDIN=https://www.linkedin.com/company/eterexchange
ENV NEXT_PUBLIC_SOCIAL_TWITTER=https://x.com/eterex_official

# Create a non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files from standalone build
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]

