/**
 * Symbol to Persian name mapping for coins
 */
export const COIN_NAMES: Record<string, string> = {
	BTC: 'بیت کوین',
	ETH: 'اتریوم',
	BNB: 'بایننس کوین',
	USDT: 'تتر',
	DOT: 'پولکادات',
	LTC: 'لایت کوین',
	DOGE: 'دوج کوین',
	XRP: 'دریپل',
	ADA: 'کاردانو',
	LUNA: 'لونا',
	ZRX: 'زیرو ایکس',
	ZIL: 'زیلیکا',
	ZEC: 'زی کش',
	YGG: 'ییلد گیلد گیمز',
	YFI: 'یرن فایننس',
	XVS: 'ونوس',
	XVG: 'ورج',
	XTZ: 'تزوس',
	XNO: 'نانو',
	XEC: 'ای کش',
	WOO: 'وو نتورک',
	WLD: 'ورلد کوین',
	WBTC: 'رپد بیت کوین',
	WAN: 'وان چین',
	VTHO: 'وی ثور توکن',
	VGX: 'وویجر',
	VET: 'وی چین',
	USDC: 'یو اس دی کوین',
	UNI: 'یونی سواپ',
	TRX: 'ترون',
	THETA: 'تتا',
	TFUEL: 'تتافیول',
	SUSHI: 'سوشی سواپ',
	STX: 'استکس',
	SOL: 'سولانا',
	SNX: 'سینتتیکس',
	SHIB: 'شیبا اینو',
	RUNE: 'ثورچین',
	QNT: 'کوانت',
	NEXO: 'نکسو',
	NEO: 'نئو',
	MKR: 'میکر',
	MATIC: 'پالیگان',
	MANA: 'دسنترالند',
	LINK: 'چین لینک',
	KSM: 'کوزاما',
	ICP: 'اینترنت کامپیوتر',
	HOT: 'هولو',
	HBAR: 'هدرا هش گراف',
	GRT: 'گراف',
	FTT: 'اف تی ایکس توکن',
	FLOW: 'فلو',
	FIL: 'فایل کوین',
	ETC: 'اتریوم کلاسیک',
	EOS: 'ایاس',
	ENJ: 'انجین کوین',
	EGLD: 'الروند',
	DCR: 'دیکرد',
	DASH: 'دش',
	DAI: 'دای',
	COMP: 'کامپاند',
	CHZ: 'چیلیز',
	CAKE: 'پنکیک سواپ',
	BCH: 'بیت کوین کش',
	AVAX: 'آوالانچ',
	AMP: 'آمپ',
	ALGO: 'الگورند',
	AAVE: 'آوی',
};

export function getCoinPersianName(symbol: string): string {
	return COIN_NAMES[symbol.toUpperCase()] ?? symbol.toUpperCase();
}
